version: '3.8'

services:
  traefik:
    image: traefik:v2.5
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"       # for lieten http
      - "8080:8080"   # for traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.yml:/traefik.yml

  nginx:
    build: ./nginx
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`nginx.localhost`)"    # address change
      - "traefik.http.services.nginx.loadbalancer.server.port=80"

  apache:
    build: ./apache
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.apache.rule=Host(`apache.localhost`)"  # address change
      - "traefik.http.services.apache.loadbalancer.server.port=80"