version: '3.8'

services:
  traefik:
    image: traefik:v2.5
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"

    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.yml:/traefik.yml

  nginx:
    build: ./nginx
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`nginx.localhost`)"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"

  apache:
    build: ./apache
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.apache.rule=Host(`apache.localhost`)"
      - "traefik.http.services.apache.loadbalancer.server.port=80"

  flask-app-1:
    build: ./flask-app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flask.rule=Host(`192.168.68.154`)"
      - "traefik.http.services.flask.loadbalancer.server.port=5000"
    depends_on:
      - db

  flask-app-2:
    build: ./flask-app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flask.rule=Host(`192.168.68.154`)"
      - "traefik.http.services.flask.loadbalancer.server.port=5000"
    depends_on:
      - db

  flask-app-3:
    build: ./flask-app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flask.rule=Host(`192.168.68.154`)"
      - "traefik.http.services.flask.loadbalancer.server.port=5000"
    depends_on:
      - db

  flask-app-4:
    build: ./flask-app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flask.rule=Host(`192.168.68.154`)"
      - "traefik.http.services.flask.loadbalancer.server.port=5000"
    depends_on:
      - db

  flask-app-5:
    build: ./flask-app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flask.rule=Host(`192.168.68.154`)"
      - "traefik.http.services.flask.loadbalancer.server.port=5000"
    depends_on:
      - db


  db:
    build: ./db
    environment:
      POSTGRES_PASSWORD: mypassword
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
