services:
  service_1:
    build: /home/user/Desktop/MIDTREM/upload-projects/HM3.
    labels:
    - traefik.enable=true
    - traefik.http.routers.service_1.rule=Host(`HM3..localhost`)
    - traefik.http.services.service_1.loadbalancer.server.port=8000
    ports:
    - 8000:8000
  service_2:
    build: /home/user/Desktop/MIDTREM/upload-projects/HM1.
    labels:
    - traefik.enable=true
    - traefik.http.routers.service_2.rule=Host(`HM1..localhost`)
    - traefik.http.services.service_2.loadbalancer.server.port=8000
    ports:
    - 8001:8000
  service_3:
    build: /home/user/Desktop/MIDTREM/upload-projects/HM2.
    labels:
    - traefik.enable=true
    - traefik.http.routers.service_3.rule=Host(`HM2..localhost`)
    - traefik.http.services.service_3.loadbalancer.server.port=8000
    ports:
    - 8002:8000
  service_4:
    build: /home/user/Desktop/MIDTREM/upload-projects/HM4.
    labels:
    - traefik.enable=true
    - traefik.http.routers.service_4.rule=Host(`HM4..localhost`)
    - traefik.http.services.service_4.loadbalancer.server.port=8000
    ports:
    - 8003:8000
  traefik:
    command:
    - --api.insecure=true
    - --providers.docker=true
    - --entrypoints.web.address=:80
    image: traefik:v2.5
    ports:
    - 80:80
    - 8080:8080
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./traefik/traefik.yml:/traefik.yml
version: '3.8'
volumes:
  db_data: {}
